import { NextResponse } from "next/server";
import prisma from "@/lib/prisma";
import { Resend } from "resend";
import { z } from "zod";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";

const contactSchema = z.object({
  name: z.string().min(1, "Name is required"),
  email: z.string().email("Invalid email address"),
  phone: z.string().min(1, "Phone number is required"),
  subject: z.string().min(1, "Subject is required"),
  message: z.string().min(1, "Message is required"),
});

export async function GET(req: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session || !["SUPER_ADMIN", "ADMIN"].includes(session.user.role)) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const messages = await prisma.contactMessage.findMany({
      orderBy: { createdAt: "desc" },
    });

    return NextResponse.json(messages);
  } catch (error) {
    console.error("Failed to fetch contact messages:", error);
    return NextResponse.json({ error: "Failed to fetch contact messages" }, { status: 500 });
  }
}

export async function POST(req: Request) {
  try {
    const body = await req.json();
    
    // Validate request body
    const result = contactSchema.safeParse(body);
    if (!result.success) {
      return NextResponse.json(
        { error: "Invalid form details", details: result.error.format() },
        { status: 400 }
      )
    }

    const { name, email, phone, subject, message } = result.data;

    // 1. Save to SQLite Database
    const savedMessage = await prisma.contactMessage.create({
      data: {
        name,
        email,
        phone,
        subject,
        message,
      },
    });

    // 2. Fetch admin email from settings
    const adminEmailSetting = await prisma.siteSettings.findUnique({
      where: { key: "contact_email" },
    });
    const toEmail = adminEmailSetting?.value || "info@firuzkabirashik.com";

    // 3. Send email via Resend if API key is present
    const resendApiKey = process.env.RESEND_API_KEY;
    const emailFrom = process.env.EMAIL_FROM || "onboarding@resend.dev";

    if (resendApiKey) {
      try {
        const resend = new Resend(resendApiKey);
        await resend.emails.send({
          from: `Firuz Portfolio <${emailFrom}>`,
          to: toEmail,
          subject: `[New Lead] - ${subject}`,
          html: `
            <div style="font-family: sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; border: 1px solid #eee; border-radius: 10px;">
              <h2 style="color: #0866ff; border-bottom: 2px solid #0866ff; padding-bottom: 10px; margin-bottom: 20px;">New Contact Lead Received</h2>
              <p>You have received a new message from the contact form on your portfolio website.</p>
              <table style="width: 100%; border-collapse: collapse; margin-top: 20px;">
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #f0f0f0; width: 120px;">Name:</td>
                  <td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;">${name}</td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #f0f0f0;">Email:</td>
                  <td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;"><a href="mailto:${email}">${email}</a></td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #f0f0f0;">Phone:</td>
                  <td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;"><a href="tel:${phone}">${phone}</a></td>
                </tr>
                <tr>
                  <td style="padding: 8px 0; font-weight: bold; border-bottom: 1px solid #f0f0f0;">Subject:</td>
                  <td style="padding: 8px 0; border-bottom: 1px solid #f0f0f0;">${subject}</td>
                </tr>
              </table>
              <div style="margin-top: 30px; padding: 15px; background-color: #f9f9f9; border-left: 4px solid #0866ff; border-radius: 4px;">
                <h4 style="margin-top: 0; margin-bottom: 10px;">Message:</h4>
                <p style="margin: 0; white-space: pre-wrap; line-height: 1.6; color: #333;">${message}</p>
              </div>
              <p style="margin-top: 30px; font-size: 12px; color: #888; text-align: center;">
                This message was automatically generated by your portfolio contact form.
              </p>
            </div>
          `,
        });
      } catch (emailError) {
        console.error("Resend failed to send email:", emailError);
        // We do not fail the request if only the email notification failed,
        // since the lead is already saved in the database!
      }
    } else {
      console.warn("RESEND_API_KEY is not defined. Skipping email sending. Message is stored in database.");
    }

    return NextResponse.json({ success: true, message: savedMessage });
  } catch (error) {
    console.error("Error processing contact form:", error);
    return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
  }
}
